name: majora
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  get_it: ^7.7.0
  isar: ^2.1.4
  pretty_dio_logger: ^1.3.1
  slang: ^3.31.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
