name: package
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  ganon:
    path: packages/ganon
  hyrule:
    path: packages/hyrule
  link:
    path: packages/link
  majora:
    path: packages/majora
  zelda:
    path: packages/zelda

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
