name: zelda
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  file: ^7.0.0
  hive: ^2.2.3
  intl: ^0.19.0
  isar: ^2.1.4
  path: ^1.9.0
  uuid: ^4.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
