name: link
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2
  logger: ^2.3.0
  # path: ^1.8.0

dev_dependencies:
  custom_lint: ^0.6.4
  lints: ^3.0.0
  test: ^1.25.7
  very_good_analysis: ^5.1.0
